# Generated by Django 3.2.7 on 2021-10-05 11:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 11, 59, 57, 624204, tzinfo=utc), verbose_name='date published'),
        ),
    ]
