# Generated by Django 3.2.7 on 2021-10-05 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 12, 32, 17, 218503, tzinfo=utc), verbose_name='date published'),
        ),
    ]
