# Generated by Django 3.2.7 on 2021-10-13 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20211005_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 13, 8, 42, 23, 866639, tzinfo=utc), verbose_name='date published'),
        ),
    ]
