# Generated by Django 3.2.7 on 2021-10-05 12:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 12, 1, 47, 185389, tzinfo=utc), verbose_name='date published'),
        ),
    ]
