# Generated by Django 3.2.7 on 2021-10-05 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20211005_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 5, 18, 42, 30, 648956, tzinfo=utc), verbose_name='date published'),
        ),
    ]
