# Generated by Django 3.2.9 on 2021-11-07 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 17, 37, 37, 554564, tzinfo=utc), verbose_name='date published'),
        ),
    ]
